### ISSUE TITLE
Not an issue. Please delete if possible.

### ISSUE THREAD

**Issue by abaile33** [springfox/springfox-demos#15]
Sorry, wrong repository, not sure how to delete an issue.

**Comment by dilipkrish** [comment]
Some of documentation code snippets assume [googles guava library](https://github.com/google/guava). So apologies if thats not clearly stated. Will make a note of that.

Couple of things here, 
- :+1: for reporting this issue!
- not sure what documentation you're referring to and why you're reporting it in this demo repository? links/screenshots would be helpful.
- All of this is open source. No one is paying anyone to do this, so we could definitely use your help _fixing_ the documentation that you find lacking. Its just a matter of creating a pull request.
- if everyone one of _the many developers_ that use this library would improve it ever so slightly be it documentation or adding tests or for that matter implementing any of [the numerous features](https://github.com/springfox/springfox/labels/feature) that are not done because there is only so much time, we'd have a way better library that doesn't take as long to fix bugs and add features.
- Lastly if you like the library please consider [starring the repo](https://github.com/springfox/springfox)
